### PR TITLE
Fix redgifs playback

### PR DESCRIPTION
**Pull request by gringofe**
Hi,

this PR fixes redgifs playback by adding the required headers.

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Thanks.

**Comment by bqv** [comment]
hey, that's my code! (lmao)

**Comment by 1fexd** [comment]
What's your code?

**Comment by bqv** [comment]
i was sure i came up with this fix ages ago, but looks like i might have just been inspired by you tbh so nevermind :D

**Comment by 1fexd** [comment]
Actually I'm not sure how I came up with the fix but I think I just looked at the headers whcih are set in the browser

**Pull request merged**
